package ir.maktab.maktabprojectstep2.idpay;

public enum StatusType {

    PAYMENT_NOT_MADE,
    PAYMENT_FAILED,
    AN_ERROR_HAS_OCCURRED,
    BLOCKED,
    RETURN_TO_PAYER,
    REVERSED_SYSTEM,
    CANCEL_PAYMENT,
    MOVED_TO_PAYMENT_GATEWAY,
    AWAITING_PAYMENT_CONFIRMATION,
    PAYMENT_IS_APPROVED,
    PAYMENT_HAS_ALREADY_BEEN_APPROVED,
    DEPOSITED_TO_THE_RECIPIENT,
    INVALID_CARD_NUMBER,
    ACCOUNT_BALANCE_IS_NOT_ENOUGH,
    THE_PASSWORD_ENTERED_IS_INCORRECT,
    THE_NUMBER_OF_REQUESTS_IS_TOO_MUCH,
    THE_NUMBER_OF_ONLINE_PAYMENTS_PER_DAY_IS_MORE_THAN_ALLOWED,
    DAILY_INTERNET_PAYMENT_IS_MORE_THAN_ALLOWED,
    INVALID_CARD_ISSUER,
    SWITCH_ERROR,
    THE_CARD_IS_NOT_AVAILABLE,
}
